
language: node_js
node_js:
  - "9"

install: yarn

cache: yarn

script:
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
  target-branch: master
  local-dir: ${TRAVIS_BUILD_DIR}/dist
  fqdn: prost-service.ru
  project-name: ProstoService/prosto_service
  repo: ProstoService/prostoservice.github.io
  keep-history: true
